//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Model
{
    public class product
    {
       
    
        public int id { get; set; }
        public string product_name { get; set; }
        public string product_intro { get; set; }
        public string product_imageurl { get; set; }
        public int product_price { get; set; }
        public Nullable<System.DateTime> crtime { get; set; }
        public Nullable<System.DateTime> uptime { get; set; }
        public Nullable<int> state { get; set; }
        public string product_content { get; set; }
    }
}
